<section class="register">

<h2>Register</h2>

<?php if ($this->error): ?>
	<p class="error">There were one or more issues with your submission. Please correct them as indicated below.</p>
<?php endif ?>

<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(NULL, array('controller'=>'Register', 'action' => 'process')));
	$form->setAttribute('method', 'post');
	echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formLabel($form->get('name')); ?>
	<?php
		echo $this->formElement($form->get('name'));
		echo $this->formElementErrors($form->get('name'));
	?>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('email')); ?>
	<?php
		echo $this->formElement($form->get('email'));
		echo $this->formElementErrors($form->get('email'));
	?>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('password'));?>
	<?php
		echo $this->formElement($form->get('password'));
		echo $this->formElementErrors($form->get('password'));
	?>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('confirm_password')); ?>
	<?php
		echo $this->formElement($form->get('confirm_password'));
		echo $this->formElementErrors($form->get('confirm_password'));
	?>
</div>

<?php
	echo $this->formElement($form->get('submit'));
	echo $this->formElementErrors($form->get('submit'));
?>


<?php echo $this->form()->closeTag() ?>


<hr><a href="/"><< Back</a>

</section>